---
- name: Create facts directory
  file:
    path: '{{ macintosh_facts_directory }}'
    state: directory

- name: Create facts file
  template:
    src: '{{ macintosh_facts_src }}'
    dest: '{{ macintosh_facts_dest }}'
    mode: '{{ macintosh_facts_mode }}'
  register: macintosh_facts_template

- name: Reload facts when changed
  setup:
    # This only gathers the "min" subset which includes our custom facts:
    gather_subset: '!all'
  when: macintosh_facts_template is changed
