---
- name: Create facts directory
  file:
    path: '{{ macintosh_facts_directory }}'
    state: directory

- name: Copy facts file
  copy:
    src: '{{ macintosh_facts_file }}'
    dest: '{{ macintosh_facts_directory }}'
    mode: '{{ macintosh_facts_mode }}'
  register: macintosh_facts

- name: Reload facts when changed
  setup:
    # This only gathers the "min" subset which includes our custom facts:
    gather_subset: '!all'
  when: macintosh_facts is changed
